version: '3.8'

services:
  node:
    build: 
      context: ./backend
    ports: 
      - "3001:3001"
    depends_on:
      - ai

  ai:
    build: 
      context: ./ai
    ports:
      - "5000:5000"
